# This file contains keys, URLs and configuration options for both GtfsTimeTable.py and TimeTableApi.py
# It needs to be located in the same directory as the python files listed above. Any setting with ';' in front of it is optional and default values will be used unless overridden in this file.

# Common values required by both GtfsTimeTable and TimeTableApi
[DEFAULT]

# Operator abbreviation is required for the application to function. Select the region you are interested
# in at https://www.trafiklab.se/api/gtfs-datasets/gtfs-regional.
# IMPORTANT! Only operators that provide real-time data are currently supported by this software. In September 2024
# the available options are: jlt, klt, krono, orebro, skane, sl, ul, vastmanland, varm, xt and otraf.
operator = skane

# This stop ID will be used uness one is provided as commandline argument or web-url. This configuration setting is not required.
;stop_id = 9021012080000000

# The default bahavior is to select all stop times matching a time-window spanning from 10 minutes ago (to catch any delayed vehicles) to 2 hours into the future.
# The maximum window size is 24 hours.
;window_size_hours = 2

# Set the verbosity of log output. This configuration setting is not required.
;log_level = INFO


# In order to download the regional data files, API keys are needed. Read https://www.trafiklab.se/docs/getting-started/using-trafiklab/
# for details. You will need one key for the GTFS static data and one for real-time updates (TripUpdates and VehiclePositions).
[API Keys]

gtfs_regional_static_data = 111x111x11111x11x11x1xx111111xxx
gtfs_regional_realtime = 11xxx11xx1111111x1111xx11x11x11x


# These are the URL's used to fetch data from TrafikLab. They are fairly static so there should be no reason to change them but if
# the app stops working, validate them on https://www.trafiklab.se/api/gtfs-datasets/gtfs-regional and update as required.
[URL]

gtfs = https://opendata.samtrafiken.se/gtfs/${operator}/${operator}.zip?key=${API Keys:gtfs_regional_static_data}
vehicle_positions = https://opendata.samtrafiken.se/gtfs-rt/${operator}/VehiclePositions.pb?key=${API Keys:gtfs_regional_realtime}
trip_updates = https://opendata.samtrafiken.se/gtfs-rt/${operator}/TripUpdates.pb?key=${API Keys:gtfs_regional_realtime}

# This section configures the webserver which is used by TimeTableApi. All configuration settings are optional.
[Webserver]

# this option will reduce memory significantly, but queries will be slow
;uncached = False

# This setting affects if the web server will reply to queries sent to localhost only (safer) or on all interfaces.
;local_only = False

# Which IP port shall the web server listen on.
;ip_port = 5000
